---
title: "Page 2 Markdown"
author: "Jonathan Molner & Diya Shreenath"
date: "10/28/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
final_four_teams <- read_csv("~/march-madness-predictor/data/Final Four Teams.csv")
conference_data <- read_csv("~/march-madness-predictor/data/mach_madness_conference_list.csv")
```

```{r}
new_data <- final_four_teams %>%
  left_join(conference_data, by = c("Team" = "Team"))
```

```{r}
new_data[is.na(new_data)] <- "Non Power 6"
```

```{r}
view(new_data)
```

```{r}
write.csv(new_data, file = "final_four_conference_data.csv")
```



```{r}
data_count <- new_data %>%
  select(Year, Conference) %>%
  count(Conference, Year)
```

```{r}
view(data_count)
```

```{r}
data_count <- data_count %>%
  group_by(Conference, n) %>%
  count()
```
### Renaming variables here
```{r}
data_count <- data_count %>%
  rename("Number of Teams Within Conference" = "n",
         "Number of Times Occurred" = "nn")
```

```{r}
data_count <- data_count %>%
  mutate(prob_occurence = (`Number of Times Occurred` / 83)*100)
```
### How to round prob occurence if needed
```{r}
data_count$prob_occurence <- round(data_count$prob_occurence, digits = 0)
```
### How to add a percentage to prob occurence
```{r}
data_count$prob_occurence <- paste0(data_count$prob_occurence, "%")
```


