---
title: "Tab 3 - FF Predictor by Seed"
author: "Jonathan Molner & Diya Shreenath"
date: "11/8/2023"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
final_four_seeds <- read_csv("~/march-madness-predictor/data/Seed Data.csv")
```

```{r}
seed_count <- final_four_seeds %>%
  select(Year, Seed) %>%
  count(Seed, Year)
```

```{r}
view(seed_count)
```

```{r}
seed_count <- seed_count %>%
  group_by(Seed, n) %>%
  count()
```

```{r}
seed_count <- seed_count %>%
rename("Number of Teams Of Given Seed in the Final Four" = "n",
         "Number of Times Occurred" = "nn")
```

```{r}
seed_count <- seed_count %>%
  mutate(prob_occurence = `Number of Times Occurred`*100 / 44)
```

```{r}
seed_count$prob_occurence <- round(seed_count$prob_occurence, digits = 0)
```

### Aesthetic Work
```{r}
seed_count$Seed[is.na(seed_count$Seed)] <- 0
seed_count$prob_occurence <- paste0(seed_count$prob_occurence, "%")
```

```{r}
seed_count$Seed <- round(seed_count$Seed, digits = 0)
```

```{r}
seed_count <- seed_count %>%
  filter(Seed != 0) %>%
  arrange(Seed)
```

```{r}
write.csv(seed_count, file = "seed_predictor.csv")
```




