---
title: "Tab 3 - FF Predictor by Conference Part 2"
author: "Jonathan Molner & Diya Shreenath"
date: "11/16/2023"
output: html_document
---

```{r}
new_data <- read_csv("~/march-madness-predictor/data/final_four_conference_data.csv")
```

```{r}
new_data <- new_data %>%
  select(Year, Conference) %>%
  count(Conference, Year)
```

```{r}
new_data <- new_data %>%
  group_by(Conference, n) %>%
  count()
```

### Renaming variables here
```{r}
new_data <- new_data %>%
  rename("Number of Teams from the Conference in the Final Four" = "n",
         "Number of Times Occurred" = "nn")
```

```{r}
new_data <- new_data %>%
  mutate(prob_occurence = (`Number of Times Occurred` / 83)*100)
```

### How to round prob occurence if needed
```{r}
new_data$prob_occurence <- round(new_data$prob_occurence, digits = 0)
```

### How to add a percentage to prob occurence
```{r}
new_data$prob_occurence <- paste0(new_data$prob_occurence, "%")
```

```{r}
write.csv(new_data, file = "conference_predictor.csv")
```
