---
title: "Probability and Additional Graphs"
author: "Jonathan Molner & Diya Shreenath"
date: "11/11/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
march_madness_data <- read_csv("~/march-madness-predictor/data/Bio_185_March_Madness_Data.csv")
```

```{r}
march_madness_data <- march_madness_data %>%
  group_by(Winner, Round) %>%
  count(Winner)
```

```{r}
win_pct_data <- march_madness_data %>%
  rename(number_of_wins = n) %>%
  ungroup(Winner) %>%
  mutate(total_games = sum(number_of_wins)) %>%
  group_by(Winner) %>%
  mutate(win_pct = number_of_wins / total_games) %>%
  select(Winner, number_of_wins, win_pct, Round)
```

```{r}
win_pct_data <- win_pct_data %>%
  mutate(Winner = as.character(Winner))
```

```{r}
win_pct_data <- win_pct_data %>%
      mutate(Winner = ifelse(Winner == "0","Underdog Won","Favorite Won"))
```


```{r}
win_pct_data <- win_pct_data %>%
  mutate(Winner = factor(Winner,
                              levels = c("Underdog Won", "Favorite Won"),
         labels = c("Underdog Won", "Favorite Won")))
```


```{r}
write.csv(win_pct_data, file = "win_percentage_by_round.csv")
```



```{r}
win_pct_data %>%
ggplot(mapping = aes(x = Round, y = win_pct, fill = Winner)) +
  geom_col()
```

### Might need to implement the round info but we will cross that bridge later if needed