---
title: "Tab 2 - Distances Traveled"
author: "Jonathan Molner & Diya Shreenath"
date: "11/1/2023"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
distance_data <- read_csv("~/march-madness-predictor/data/Bio 185 March Madness Data Lats.csv")
final_four_teams <- read_csv("~/march-madness-predictor/data/Final Four Teams.csv")
```

```{r}
haversine <- function(long1, lat1, long2, lat2, round = 3) {
  # convert to radians
  long1 = long1 * pi / 180
  lat1  = lat1  * pi / 180
  long2 = long2 * pi / 180
  lat2  = lat2  * pi / 180
  
  R = 6371 # Earth mean radius in km
  
  a = sin((lat2 - lat1)/2)^2 + cos(lat1) * cos(lat2) * sin((long2 - long1)/2)^2
  d = R * 2 * asin(sqrt(a))
  
  return( round(d,round) ) # distance in km
}
```

```{r}
distance_data <- distance_data %>%
  mutate(distance_favorite = haversine(College_lon, College_lat, `Lon for City Where Game was Played`, `Lat for City Where Game was played`, round = 0))
```

```{r}
distance_data <- distance_data %>%
  mutate(distance_underdog = haversine(Underdog_lon, Underdog_lat, `Lon for City Where Game was Played`, `Lat for City Where Game was played`, round = 0))
```

```{r}
distance_data <- distance_data %>%
  select(Year, Favorite, Underdog, distance_favorite, distance_underdog, Round)
```

```{r}
favorite_data_table <- distance_data %>%
  select(Year, Favorite, distance_favorite, Round) %>%
  group_by(Favorite, Year) %>%
  mutate(total_distance_favorite = sum(distance_favorite))
```

```{r}
underdog_data_table <- distance_data %>%
  select(Year, Underdog, distance_underdog, Round) %>%
  group_by(Underdog, Year) %>%
  mutate(total_underdog_distance = sum(distance_underdog))
```


```{r}
favorite_data_table <- favorite_data_table %>%
  mutate(team_name = Favorite)
```

```{r}
underdog_data_table <- underdog_data_table %>%
  mutate(team_name = Underdog)
```

```{r}
total_team_distance_traveled <- full_join(favorite_data_table, underdog_data_table, by = c("Year" = "Year", "team_name" = "team_name"))
```

```{r}
total_team_distance_traveled <- total_team_distance_traveled %>%
  mutate(total_team_travel = (total_distance_favorite + total_underdog_distance))
```

```{r}
total_team_distance_traveled$total_underdog_distance[is.na(total_team_distance_traveled$total_underdog_distance)] <- 0
total_team_distance_traveled$total_distance_favorite[is.na(total_team_distance_traveled$total_distance_favorite)] <- 0
total_team_distance_traveled$total_team_travel[is.na(total_team_distance_traveled$total_team_travel)] <- 0
```

```{r}
total_team_distance_traveled <- total_team_distance_traveled %>%
  group_by(team_name, Year) %>%
  mutate(kilometers_traveled = pmax(total_distance_favorite, total_underdog_distance, total_team_travel))
```

```{r}
total_team_distance_traveled %>%
  select(Year, team_name, kilometers_traveled,)
```

#created 750 rows because for each team who has distance data as a favorite and an underdog shows up with 3 entries in the original table because data for underdog and favorite automatically means data for total distance travelened

```{r}
total_team_distance_traveled <- unique(total_team_distance_traveled[, c("team_name", "Year", "kilometers_traveled")])
```

#the new dataset has 332 rows after filtering out duplicates


```{r}
total_team_distance_traveled
```

```{r}
total_team_distance_traveled <- total_team_distance_traveled %>%
  inner_join(final_four_teams, by = c("Year" = "Year", "team_name" = "Team"))
```

```{r}
total_team_distance_traveled <- total_team_distance_traveled %>%
  mutate(miles_traveled = kilometers_traveled * .621371)
```

```{r}
total_team_distance_traveled$miles_traveled <- round(total_team_distance_traveled$miles_traveled, digits = 0)
```

```{r}
total_team_distance_traveled <- total_team_distance_traveled %>%
  arrange(team_name)
```

```{r}
write.csv(total_team_distance_traveled, file = "total_distance_traveled.csv")
```

```{r}
UNC_EX <- total_team_distance_traveled %>%
  filter(team_name == "UNC") %>%
  select(miles_traveled)
```

```{r}
total_team_distance_traveled %>%
  ggplot(mapping = aes(x = miles_traveled)) +
  geom_density() +
  geom_vline(aes(xintercept = miles_traveled, color = factor(Year)), data = UNC_EX) +
  labs(color = "Year")
```