---
title: "Tab 1 - Game Locations"
author: "Jonathan Molner & Diya Shreenath"
date: "10/25/2023"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
march_madness_data <- read_csv("~/march-madness-predictor/data/Bio_185_March_Madness_Data.csv")
```

```{r}
view(march_madness_data)
```

```{r}
march_madness_data <- march_madness_data %>%
  rename(lat = `Lat for City Where Game was played`,
         lng = `Lon for City Where Game was Played`,
         distance_favorite = `Distance to Favorite`,
         game_city = `City Where Game Was Played`,
         game_state = `State Where Game was Played`)
```

```{r}
game_total <- march_madness_data %>%
  count(lat, lng, game_city)
```

```{r}
view(game_total)
```

```{r}
game_total$popup_text <- paste0(game_total$game_city, ": ", game_total$n, " games")
```

```{r}
library(leaflet)
library(ggplot2)
```

#Write the CSV
```{r}
write.csv(game_total, file = "game_location_data.csv")
```

```{r}
leaflet(data = game_total) %>% 
  setView(lng = -96.25, lat = 39.5, zoom = 4) %>%
  addTiles()%>%
  addCircleMarkers(radius = ~n, label = ~popup_text)
```



