---
title: "Tab 4 - Historical Performance"
author: "Jonathan Molner & Diya Shreenath"
date: "11/13/2023"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)
```

```{r}
historical_data <- read_csv("~/march-madness-predictor/data/Bio_185_March_Madness_Data.csv")
```

```{r}
favorite_maximum_round <- historical_data %>%
  group_by(Favorite, Year) %>%
  mutate(maximum_round_favorite = max(Round)) %>%
  select(Year, Favorite, maximum_round_favorite)
```

```{r}
underdog_maximum_round <- historical_data %>%
  group_by(Underdog, Year) %>%
  mutate(maximum_round_underdog = max(Round)) %>%
  select(Year, Underdog, maximum_round_underdog)
```

```{r}
aggregate_maximum_round <- full_join(favorite_maximum_round, underdog_maximum_round, by = c("Year" = "Year", "Favorite" = "Underdog"))
```

```{r}
aggregate_maximum_round$maximum_round_favorite[is.na(aggregate_maximum_round$maximum_round_favorite)] <- 0
aggregate_maximum_round$maximum_round_underdog[is.na(aggregate_maximum_round$maximum_round_underdog)] <- 0
```

```{r}
aggregate_maximum_round <- aggregate_maximum_round %>%
  group_by(Year, Favorite) %>%
  mutate(final_round = pmax(maximum_round_favorite, maximum_round_underdog)) %>%
  rename("Team" = "Favorite") %>%
  select(Year, Team, final_round) %>%
  distinct() %>%
  arrange(Team)
```

```{r}
aggregate_maximum_round <- aggregate_maximum_round %>%
  mutate(Round_Reached = factor(final_round,
                              levels = c(1, 2, 3, 4, 5, 6),
         labels = c("First Round", "Second Round", "Sweet Sixteen", "Elite Eight", "Final Four", "Championship Game")))
```

```{r}
aggregate_maximum_round$Year <- round(aggregate_maximum_round$Year, digits = 0)
```

```{r}
write.csv(aggregate_maximum_round, file = "historical_performance.csv")
```

```{r}
aggregate_maximum_round %>%
  filter(Team == "Abilene Christian") %>%
  ggplot(mapping = aes(x = Year, y = Round_Reached)) +
  geom_tile() +
  scale_x_continuous(breaks = seq(min(aggregate_maximum_round$Year), max(aggregate_maximum_round$Year), by = 1)) +
  coord_cartesian(xlim = c(2013, 2023))
```

